inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - '*.rb'
    - '*.ru'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false