default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  enablessl: false
  username: postgres
  password: admin
  host: 127.0.0.1
  port: 5432


development:
  <<: *default
  database: app_pump_dev
  schema_search_path: myapp,sharedapp,public
test:
  <<: *default
  database: app_pump_test