default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: aws-0-eu-west-1.pooler.supabase.com
  port: 5432
  username: postgres.ccjiyccxtfegpxxvckpl
  password: pumpdatabase123@
  database: postgres

development:
  <<: *default

test:
  <<: *default

production:
  primary: &primary_production
    <<: *default
  cache:
    <<: *primary_production
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    migrations_paths: db/cable_migrate
